export const projects = [
  {
    title: 'Ascend',
    eyebrow: 'Personal AI Photoshoot',
    status: { label: 'Building', tone: 'build' },
    description:
      'Privacy-first identity model training + local AI portrait generation. Fine-tunes a lightweight LoRA on Stable Diffusion for fast, repeatable, offline “photoshoots” on consumer GPUs.',
    highlights: [
      'Trains a personalized identity model from 10–30 photos',
      'Local LoRA fine-tuning for fast reuse + style consistency',
      'Job-based pipeline with progress tracking + artifact logs',
      'Fully offline inference (no cloud GPU dependency)',
    ],
    tags: ['Stable Diffusion', 'LoRA', 'PyTorch', 'Diffusers', 'FastAPI', 'SQLite', 'CUDA', 'FP16'],
    logos: ['python', 'pytorch', 'huggingface', 'fastapi', 'sqlite', 'nvidia'],
    timeframe: 'TOOLS USED',
    cta: { label: 'Coming Soon', href: '#contact' },
    accent: { from: '#22d3ee', via: '#6366f1', to: '#a855f7' },
  },
  {
    title: 'AInstein',
    eyebrow: 'Automation',
    status: { label: 'Building', tone: 'build' },
    description:
      'Python content automation that takes a Short from idea → script → voice → video → upload with minimal manual work. Designed with stage-by-stage debug commands and a practical “ship even if clips fail” fallback path.',
    highlights: [
      'GPT generates title/hook/script + metadata + Sora-ready visual prompts',
      'Optional Sora automation via Playwright (reuse real Chrome profile via remote debugging)',
      'ElevenLabs TTS narration + ffmpeg stitching (clips or black-frame fallback)',
      'Uploads via YouTube Data API v3 with OAuth2 + refreshable local token',
    ],
    tags: [
      'Python',
      'OpenAI API',
      'Playwright',
      'Sora',
      'ElevenLabs',
      'YouTube Data API v3',
      'OAuth2',
      'ffmpeg',
      'python-dotenv',
      'requests',
      'JSON',
    ],
    logos: ['python', 'youtube', 'google', 'ffmpeg', 'elevenlabs', 'openai', 'playwright', 'sora'],
    timeframe: 'TOOLS USED',
    cta: { label: 'Coming Soon', href: '#contact' },
    accent: { from: '#22c55e', via: '#06b6d4', to: '#3b82f6' },
  },
  {
    title: 'SignalForge',
    eyebrow: 'Insight Engine',
    status: { label: 'Concept', tone: 'muted' },
    description:
      'Automated insight engine for social/content performance. It turns raw metrics (views, retention, likes, comments, timing) into actionable recommendations—no dead dashboards.',
    highlights: [
      'Upload CSV or connect APIs to ingest performance data',
      'Auto-detect patterns: drop-off points, posting windows, content themes',
      'LLM-generated recommendations + weekly strategy summary',
      'Built to answer “why” and “what to do next,” not just show charts',
    ],
    tags: ['Python', 'Pandas', 'NumPy', 'LLM', 'FastAPI', 'React', 'Next.js', 'Analytics'],
    logos: ['python', 'pandas', 'numpy', 'fastapi', 'react', 'nextjs', 'openai'],
    timeframe: 'TOOLS USED',
    cta: { label: 'Coming Soon', href: '#contact' },
    accent: { from: '#fb7185', via: '#f59e0b', to: '#22c55e' },
  },
  {
    title: 'Blueprint',
    eyebrow: 'Orchestration',
    status: { label: 'Concept', tone: 'muted' },
    description:
      'An AI system that converts loose ideas into production-ready assets. Instead of chatty outputs, it generates structured artifacts you can ship: component hierarchies, copy sections, theme tokens, and file-ready exports.',
    highlights: [
      'Input → goal decomposition → step-by-step artifact generation',
      'Deterministic JSON outputs with validators (less “LLM drift”)',
      'Exports: HTML + slide/PPTX-ready structures (optional)',
      'Designed as a thinking/orchestration system, not a chatbot',
    ],
    tags: [
      'Python',
      'LLM orchestration',
      'Prompt pipelines',
      'Validators',
      'Deterministic JSON',
      'FastAPI',
      'React',
      'HTML generation',
      'PPTX generation',
    ],
    logos: ['python', 'fastapi', 'react', 'html5', 'openai'],
    timeframe: 'TOOLS USED',
    cta: { label: 'Coming Soon', href: '#contact' },
    accent: { from: '#60a5fa', via: '#a78bfa', to: '#f472b6' },
  },
]

